# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  thesis-postgresql:
    container_name: thesis-postgresql
    image: postgres:14.5
    volumes:
      - ~/volumes/jhipster/Thesis/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=Thesis
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
  thesis-kafka:
    container_name: thesis-kafka
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: thesis-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://thesis-kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: thesis-kafka
  thesis-zookeeper:
    container_name: thesis-zookeper
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  thesis-mqtt:
    container_name: thesis-mqtt
    image: vernemq/vernemq:1.12.3-alpine
    restart: always
    environment:
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: 'on'
      DOCKER_VERNEMQ_ACCEPT_EULA: 'yes'
    ports:
      - '8884:8884'
      - '1883:1883'
    expose:
      - '8884'
    volumes:
      - ./mqtt/scripts:/etc/scripts
  thesis-influxdb:
    container_name: thesis-influxdb
    image: influxdb:latest
    environment:
      DOCKER_INFLUXDB_INIT_CLI_CONFIG_NAME: 'devprofile'
      DOCKER_INFLUXDB_INIT_MODE: 'setup'
      DOCKER_INFLUXDB_INIT_USERNAME: 'admin'
      DOCKER_INFLUXDB_INIT_PASSWORD: 'password'
      DOCKER_INFLUXDB_INIT_ORG: 'kry'
      DOCKER_INFLUXDB_INIT_BUCKET: 'thesis'
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: 'token'
    volumes:
      # Mount for influxdb data directory and configuration
      - ./influxdb/influxdbv2:/var/lib/influxdb2:rw
    ports:
      - '8086:8086'
